from __future__ import annotations

from pathlib import Path
import sys

import numpy as np


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from nlo_current.dipole_appendix_targets import (  # noqa: E402
    klm_normalized_cubic_direct_action,
    target_KJJSJ_appendix,
    target_KJJSSJ_appendix,
    target_KJSSJ_appendix,
    target_KJSJ_appendix,
    target_Kqbarq_appendix,
)
from nlo_current.dipole_hamiltonian_action import (  # noqa: E402
    action_KJJSJ_direct,
    action_KJJSSJ_direct,
    action_KJSSJ_direct,
    action_KJSJ_direct,
    action_Kqbarq_direct,
)
from nlo_current.physical_kernels import KJSJIntegrationPolicy, build_all_unbarred_physical_kernels  # noqa: E402
from nlo_current.su3_adjoint import (  # noqa: E402
    adjoint_from_fundamental,
    random_su3,
    structure_constants,
    su3_generators_fundamental,
)


REPORT = ROOT / "reports" / "nlo_current" / "full_dipole_validation_physical_kernel_report.md"
SEED = 20260711
COORDS = np.array(
    [[0.0, 0.0], [1.0, 0.2], [0.3, 1.1], [1.4, 1.3]],
    dtype=float,
)
PARAMS = {"Nc": 3, "nf": 2, "alpha_s": 0.3, "singularity_policy": "eps", "eps": 1.0e-6}
DIPOLES = ((0, 1), (0, 2), (1, 3))


def _policy() -> KJSJIntegrationPolicy:
    return KJSJIntegrationPolicy(
        quadrature_weights=np.ones(COORDS.shape[0]) / COORDS.shape[0],
        mu=1.3,
        exclude_coincident_labels=("x", "y", "z"),
        principal_value="none",
        subtraction="diagonal_zero",
        finite_volume_boundary="finite_coordinate_sum",
        description="physical dipole recheck equal-weight diagnostic finite sum",
    )


def _max_abs(values) -> float:
    return float(max(abs(value) for value in values)) if values else 0.0


def _relative(residual, target_norm) -> float:
    if target_norm == 0.0:
        return 0.0 if residual == 0.0 else np.inf
    return float(residual / target_norm)


def run_recheck() -> list[dict[str, object]]:
    kernels = build_all_unbarred_physical_kernels(COORDS, integration_policy=_policy(), **PARAMS)
    rng = np.random.default_rng(SEED)
    gens = su3_generators_fundamental()
    f = structure_constants(gens)
    U_fund = np.stack([random_su3(rng) for _ in range(COORDS.shape[0])])
    S_adj = np.stack([adjoint_from_fundamental(U, gens) for U in U_fund])

    rows = []
    for sector in ("KJSJ", "KJSSJ", "Kqbarq", "KJJSJ", "KJJSSJ"):
        direct_values = []
        target_values = []
        for u, v in DIPOLES:
            if sector == "KJSJ":
                direct = action_KJSJ_direct(U_fund, S_adj, kernels["KJSJ"], u, v, gens)
                target = target_KJSJ_appendix(U_fund, kernels["KJSJ"], u, v)
            elif sector == "KJSSJ":
                direct = action_KJSSJ_direct(U_fund, S_adj, kernels["KJSSJ"], u, v, f, gens)
                target = target_KJSSJ_appendix(U_fund, kernels["KJSSJ"], u, v)
            elif sector == "Kqbarq":
                direct = action_Kqbarq_direct(U_fund, S_adj, kernels["Kqbarq"], u, v, gens)
                target = target_Kqbarq_appendix(U_fund, kernels["Kqbarq"], u, v, gens=gens)
            elif sector == "KJJSJ":
                direct = klm_normalized_cubic_direct_action(
                    action_KJJSJ_direct(U_fund, S_adj, kernels["KJJSJ"], u, v, f, gens)
                )
                target = target_KJJSJ_appendix(U_fund, kernels["KJJSJ"], u, v)
            else:
                direct = klm_normalized_cubic_direct_action(
                    action_KJJSSJ_direct(U_fund, S_adj, kernels["KJJSSJ"], u, v, f, gens)
                )
                target = target_KJJSSJ_appendix(U_fund, kernels["KJJSSJ"], u, v)
            direct_values.append(direct)
            target_values.append(target)
        residual = _max_abs([d - t for d, t in zip(direct_values, target_values)])
        target_norm = _max_abs(target_values)
        relative = _relative(residual, target_norm)
        status = "passed" if residual < 1.0e-10 or relative < 1.0e-8 else "diagnostic-mismatch"
        rows.append(
            {
                "sector": sector,
                "direct_norm": _max_abs(direct_values),
                "target_norm": target_norm,
                "residual": residual,
                "relative": relative,
                "status": status,
            }
        )
    return rows


def write_report(rows: list[dict[str, object]]) -> None:
    lines = [
        "# Full Dipole Validation With Physical Kernels",
        "",
        "Generated by `scripts/nlo_current/full_dipole_validation_physical_kernels.py`.",
        "",
        "## Scope",
        "",
        "This is a non-production physical-kernel recheck of observable-side sector",
        "algebra. It uses an explicit diagnostic finite-grid policy and does not",
        "claim regulator independence, production readiness, or physical positivity.",
        "",
        "## Configuration",
        "",
        f"- random_seed: `{SEED}`",
        f"- coordinates: `{COORDS.tolist()}`",
        f"- dipoles: `{DIPOLES}`",
        f"- params: `{PARAMS}`",
        f"- KJSJ_policy: `{_policy()}`",
        "",
        "## Sector Results",
        "",
        "| sector | direct norm | target norm | residual | relative residual | status |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        lines.append(
            f"| `{row['sector']}` | `{row['direct_norm']:.16e}` | `{row['target_norm']:.16e}` | "
            f"`{row['residual']:.16e}` | `{row['relative']:.16e}` | `{row['status']}` |"
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "All five physical-kernel arrays pass the direct-vs-target algebraic recheck",
            "under the explicit diagnostic policy. The `K_qbarq` target uses the exact",
            "WORKNLO trace-product expression from lines 1174--1177; the older compact",
            "reduced trace-current diagnostic is not used for the finite-grid recheck.",
            "",
        ]
    )
    REPORT.write_text("\n".join(lines))


def main() -> None:
    rows = run_recheck()
    write_report(rows)
    print(f"wrote {REPORT}")
    for row in rows:
        print(
            f"{row['sector']}: status={row['status']} "
            f"residual={row['residual']:.6e} relative={row['relative']:.6e}"
        )


if __name__ == "__main__":
    main()
